sonar.projectKey=devalign_devalign-api
sonar.organization=devalign
sonar.python.version=3.12

# Path to the source code to be analyzed
sonar.sources=src
sonar.tests=tests

# Coverage reports configuration
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.coverage.exclusions=**/alembic/**,**/tests/**
sonar.exclusions=**/alembic/**
