"""alter_vector_dimensions

Revision ID: 3e85e88d6528
Revises: af8815637327
Create Date: 2026-06-10 01:33:15.425983

"""

from collections.abc import Sequence

import pgvector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e85e88d6528"
down_revision: str | None = "af8815637327"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE clusters SET centroid_vec = NULL")
    op.execute("UPDATE profiles SET cv_embedding = NULL")
    op.alter_column(
        "clusters",
        "centroid_vec",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.VECTOR(dim=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "cv_embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.VECTOR(dim=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE profiles SET cv_embedding = NULL")
    op.execute("UPDATE clusters SET centroid_vec = NULL")
    op.alter_column(
        "profiles",
        "cv_embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1024),
        type_=pgvector.sqlalchemy.VECTOR(dim=384),
        existing_nullable=True,
    )
    op.alter_column(
        "clusters",
        "centroid_vec",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1024),
        type_=pgvector.sqlalchemy.VECTOR(dim=384),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
