"""add_esco_and_ict_evidence_fields

Revision ID: 42d733c42950
Revises: 9354eebfaceb
Create Date: 2026-06-28 16:49:34.134966

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42d733c42950"
down_revision: str | None = "9354eebfaceb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_skill_trends",
        sa.Column("trend_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "frequency", sa.Numeric(precision=5, scale=2), server_default="0.0", nullable=False
        ),
        sa.Column(
            "importance_score",
            sa.Numeric(precision=5, scale=2),
            server_default="0.0",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.cluster_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.skill_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trend_id"),
    )
    op.create_index(
        op.f("ix_cluster_skill_trends_cluster_id"),
        "cluster_skill_trends",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_skill_trends_recorded_at"),
        "cluster_skill_trends",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_skill_trends_skill_id"), "cluster_skill_trends", ["skill_id"], unique=False
    )
    op.add_column(
        "profile_skills",
        sa.Column("self_taught", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "profile_skills",
        sa.Column("personal_projects", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "profile_skills",
        sa.Column("years_of_experience", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "profile_skills",
        sa.Column("has_certification", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "profile_skills",
        sa.Column(
            "ict_score", sa.Numeric(precision=5, scale=2), server_default="0.0", nullable=False
        ),
    )
    op.add_column("skills", sa.Column("esco_uri", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_skills_esco_uri"), "skills", ["esco_uri"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skills_esco_uri"), table_name="skills")
    op.drop_column("skills", "esco_uri")
    op.drop_column("profile_skills", "ict_score")
    op.drop_column("profile_skills", "has_certification")
    op.drop_column("profile_skills", "years_of_experience")
    op.drop_column("profile_skills", "personal_projects")
    op.drop_column("profile_skills", "self_taught")
    op.drop_index(op.f("ix_cluster_skill_trends_skill_id"), table_name="cluster_skill_trends")
    op.drop_index(op.f("ix_cluster_skill_trends_recorded_at"), table_name="cluster_skill_trends")
    op.drop_index(op.f("ix_cluster_skill_trends_cluster_id"), table_name="cluster_skill_trends")
    op.drop_table("cluster_skill_trends")
    # ### end Alembic commands ###
