"""add_embedding_to_skills

Revision ID: 6e185a40579f
Revises: 6e80d94abe6a
Create Date: 2026-06-14 02:20:40.478698

"""
from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e185a40579f'
down_revision: str | None = '6e80d94abe6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_diagnostic_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_status'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.add_column('skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'embedding')
    op.create_table('roadmaps',
    sa.Column('roadmap_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('diagnostic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roadmap_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'generating'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.diagnostic_id'], name=op.f('roadmaps_diagnostic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id', name=op.f('roadmaps_pkey'))
    )
    op.create_index(op.f('ix_roadmaps_status'), 'roadmaps', ['status'], unique=False)
    op.create_index(op.f('ix_roadmaps_diagnostic_id'), 'roadmaps', ['diagnostic_id'], unique=False)
    # ### end Alembic commands ###
