"""add_domain_and_cluster_insights

Revision ID: 6e80d94abe6a
Revises: 6f7738c1f473
Create Date: 2026-06-13 02:30:04.560970

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e80d94abe6a"
down_revision: str | None = "6f7738c1f473"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters",
        sa.Column(
            "compatible_roles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "clusters",
        sa.Column(
            "market_insights",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("skills", sa.Column("domain", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "domain")
    op.drop_column("clusters", "market_insights")
    op.drop_column("clusters", "compatible_roles")
    # ### end Alembic commands ###
