"""add_skill_weight_and_cluster_offer_count

Revision ID: 6f7738c1f473
Revises: 3e85e88d6528
Create Date: 2026-06-12 23:37:21.102713

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f7738c1f473"
down_revision: str | None = "3e85e88d6528"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters", sa.Column("job_offer_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "skills",
        sa.Column("weight", sa.Numeric(precision=5, scale=2), server_default="1.0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "weight")
    op.drop_column("clusters", "job_offer_count")
    # ### end Alembic commands ###
