"""increase_skill_name_length

Revision ID: 75e453970cbd
Revises: 42d733c42950
Create Date: 2026-06-28 17:01:13.477054

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75e453970cbd"
down_revision: str | None = "42d733c42950"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
