"""knowledge_graph_skills

Revision ID: 91474942c0b8
Revises: 6e185a40579f
Create Date: 2026-06-19 01:24:11.555635

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '91474942c0b8'
down_revision: str | None = '6e185a40579f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_aliases',
    sa.Column('alias_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=150), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_skill_aliases_alias_name'), 'skill_aliases', ['alias_name'], unique=True)
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    op.create_table('skill_relations',
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('source_skill_id', sa.UUID(), nullable=False),
    sa.Column('target_skill_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index(op.f('ix_skill_relations_source_skill_id'), 'skill_relations', ['source_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_relations_target_skill_id'), 'skill_relations', ['target_skill_id'], unique=False)
    op.add_column('skills', sa.Column('nature', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('domain_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('skills', 'domain')
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('domain', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('skills', 'domain_tags')
    op.drop_column('skills', 'nature')
    op.drop_index(op.f('ix_skill_relations_target_skill_id'), table_name='skill_relations')
    op.drop_index(op.f('ix_skill_relations_source_skill_id'), table_name='skill_relations')
    op.drop_table('skill_relations')
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias_name'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    # ### end Alembic commands ###
