"""create_profile_skills_table

Revision ID: 9354eebfaceb
Revises: dbd782abdd17
Create Date: 2026-06-27 09:26:10.682435

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9354eebfaceb"
down_revision: str | None = "dbd782abdd17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_skills",
        sa.Column("profile_skill_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.profile_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.skill_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_skill_id"),
    )
    op.create_index(
        op.f("ix_profile_skills_profile_id"), "profile_skills", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_profile_skills_skill_id"), "profile_skills", ["skill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_skills_skill_id"), table_name="profile_skills")
    op.drop_index(op.f("ix_profile_skills_profile_id"), table_name="profile_skills")
    op.drop_table("profile_skills")
    # ### end Alembic commands ###
