"""Add cv_id to profiles

Revision ID: af8815637327
Revises: c412290f9981
Create Date: 2026-06-01 12:56:52.121462

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af8815637327"
down_revision: str | None = "c412290f9981"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnostics_cluster_id"), table_name="diagnostics")
    op.create_index(
        op.f("ix_diagnostics_detected_cluster_id"),
        "diagnostics",
        ["detected_cluster_id"],
        unique=False,
    )
    op.add_column("profiles", sa.Column("cv_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("profiles_user_id_key"), "profiles", type_="unique")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("profiles_user_id_key"), "profiles", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("profiles", "cv_id")
    op.drop_index(op.f("ix_diagnostics_detected_cluster_id"), table_name="diagnostics")
    op.create_index(
        op.f("ix_diagnostics_cluster_id"), "diagnostics", ["detected_cluster_id"], unique=False
    )
    # ### end Alembic commands ###
