"""add_core_domains_to_skills

Revision ID: dbd782abdd17
Revises: 91474942c0b8
Create Date: 2026-06-26 21:37:51.792195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbd782abdd17'
down_revision: Union[str, None] = '91474942c0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('core_domains', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'core_domains')
    # ### end Alembic commands ###
